@startuml
package "チャットメッセンジャーサービス" {
    [クライアント] -down-> [CLI]
    [クライアント] -down-> [クライアントUDPソケット]

    package "サーバシステム" {
        [サーバ]
        [リレーシステム]
        [サーバUDPソケット]

        [サーバ] -down-> [リレーシステム]
        [サーバ] -down-> [サーバUDPソケット]
    }

    [CLI] -down-> [サーバ] : 接続要求
    [サーバ] -down-> [CLI] : 接続確立確認
    [CLI] -down-> [サーバ] : メッセージ送信
    [サーバ] -down-> [CLI] : メッセージ配信
}

@enduml
